name: TCExpressReloaded
api-version: 1.17
main: org.Mo_Ink.TCExpressR
version: 0.2.3
author: Mo_Ink
description: A plugin that allow renamed minecarts run faster on straight rails. Original ver：TCExpress by i@thetd.me